Repository VocaDB/vocadb, pull requests merged in 2021-05, with the labels that each got.

#863 Enable eslint
  VocaDbWeb/.eslintrc.json
  VocaDbWeb/package-lock.json
  VocaDbWeb/package.json
Labels: frontend

#870 Dispose FileStream
  VocaDbWeb/Code/Web/AspNetCoreHttpPostedFile.cs
Labels: backend, songs

#856 Artist url parser for twitter
  Tests/Service/Helpers/ArtistExternalUrlParserTests.cs
  Tests/Service/Search/Artists/ArtistSearchTests.cs
  VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs
  VocaDbModel/Service/Search/Artists/ArtistSearch.cs
Labels: feedback-wanted

#879 Convert callback to Promise
  VocaDbWeb/Scripts/Helpers/AjaxHelper.ts
  VocaDbWeb/Scripts/Repositories/AdminRepository.ts
  VocaDbWeb/Scripts/Repositories/AlbumRepository.ts
  VocaDbWeb/Scripts/Repositories/ArtistRepository.ts
  VocaDbWeb/Scripts/Repositories/PVRepository.ts
  VocaDbWeb/Scripts/Repositories/SongRepository.ts
  VocaDbWeb/Scripts/Repositories/TagRepository.ts
  VocaDbWeb/Scripts/Repositories/UserRepository.ts
  VocaDbWeb/Scripts/Shared/HttpClient.ts
  VocaDbWeb/Scripts/Shared/TopBar.ts
  VocaDbWeb/Scripts/SongList/Import.ts
  VocaDbWeb/Scripts/Tests/TestSupport/FakeSongRepository.ts
  VocaDbWeb/Scripts/User/Details.ts
  VocaDbWeb/Scripts/ViewModels/Album/AlbumDetailsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/Artist/ArtistDetailsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/ArtistCreateViewModel.ts
  VocaDbWeb/Scripts/ViewModels/PVs/PVListEditViewModel.ts
  VocaDbWeb/Scripts/ViewModels/ReleaseEvent/EventSeriesDetailsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/ReleaseEvent/ReleaseEventDetailsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/Song/SongDetailsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/Song/SongWithPreviewViewModel.ts
  VocaDbWeb/Scripts/ViewModels/SongList/ImportSongListViewModel.ts
  VocaDbWeb/Scripts/ViewModels/SongList/SongListViewModel.ts
  VocaDbWeb/Scripts/ViewModels/User/MySettingsViewModel.ts
  VocaDbWeb/Scripts/ViewModels/User/UserDetailsViewModel.ts
  VocaDbWeb/Scripts/libs.js
  VocaDbWeb/Scripts/typings/jquery.d.ts
Labels: frontend, refactor

#880 Add SongList to TagTargetTypes
  Tests/Domain/Tags/TagTargetTypesTests.cs
  VocaDbModel/Domain/Tags/TagTargetTypes.cs
Labels: api, tags
