Repository VocaDB/vocadb, pull requests merged in 2021-04, with the labels that each got.

#826 Add translation for Cover artist
  VocaDbModel/Resources/ArtistTypeNames.ja.resx
Labels: translation

#827 Add CoverArtist as option for associated artist
  VocaDbWeb/Views/Artist/Edit.cshtml
Labels: artists, frontend

#820 Song Creation form is not sufficiently user friendly #305
  VocaDbModel/Resources/Views/SongRes.de.resx
  VocaDbModel/Resources/Views/SongRes.es.resx
  VocaDbModel/Resources/Views/SongRes.ja.resx
  VocaDbModel/Resources/Views/SongRes.pt.resx
  VocaDbModel/Resources/Views/SongRes.resx
  VocaDbWeb.Resources/Resources/Views/Artist/CreateStrings.resx
  VocaDbWeb.Resources/Resources/Views/Shared/EntryCreateStrings.de.resx
  VocaDbWeb.Resources/Resources/Views/Shared/EntryCreateStrings.ja.resx
  VocaDbWeb.Resources/Resources/Views/Shared/EntryCreateStrings.resx
  VocaDbWeb.Resources/Resources/Views/Song/CreateStrings.de.resx
  VocaDbWeb.Resources/Resources/Views/Song/CreateStrings.ja.resx
  VocaDbWeb.Resources/Resources/Views/Song/CreateStrings.resx
  VocaDbWeb/Views/Song/Create.cshtml
  VocaDbWeb/wwwroot/Content/Styles/DarkAngel.less
  VocaDbWeb/wwwroot/Content/Styles/base.less
Labels: frontend, songs

#839 Alerts in one column
  VocaDbModel/Resources/Views/SongRes.resx
  VocaDbWeb/Views/Shared/KnockoutPartials/_DuplicateEntriesMessage.cshtml
  VocaDbWeb/Views/Song/Create.cshtml
  VocaDbWeb/wwwroot/Content/Styles/Overrides.less
Labels: frontend

#844 Add skeb.jp to WebLinkMatcher
  VocaDbWeb/wwwroot/Content/ExtIcons/skeb.png
  VocaDbWeb/wwwroot/Content/Styles/ExtLinks.less
  VocaDbWeb/wwwroot/Scripts/Shared/WebLinkMatcher.ts
Labels: frontend, icons

#836 Autofill label from URL when adding lyrics to a song
  VocaDbWeb/Views/Song/Partials/_LyricsForSongEdit.cshtml
  VocaDbWeb/wwwroot/Scripts/ViewModels/Song/LyricsForSongEditViewModel.ts
Labels: frontend, songs

#848 Convert to interpolated string
  VocaDbWeb/wwwroot/Scripts/Repositories/AlbumRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/ArtistRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/CommentRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/DiscussionRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/ReleaseEventRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/ResourceRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/SongListRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/SongRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/TagRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/UserRepository.ts
  VocaDbWeb/wwwroot/Scripts/Repositories/VenueRepository.ts
Labels: frontend
