Repository VocaDB/vocadb, pull requests merged in 2021-02, with the labels that each got.

#785 More favicons and URL templates
  VocaDbWeb/wwwroot/Content/ExtIcons/diversedirect.png
  VocaDbWeb/wwwroot/Content/ExtIcons/grepshop.png
  VocaDbWeb/wwwroot/Content/ExtIcons/kkbox.png
  VocaDbWeb/wwwroot/Content/ExtIcons/musicbook.png
  VocaDbWeb/wwwroot/Content/ExtIcons/mysound.png
  VocaDbWeb/wwwroot/Content/ExtIcons/oricon.png
  VocaDbWeb/wwwroot/Content/ExtIcons/ototoy.png
  VocaDbWeb/wwwroot/Content/ExtIcons/potune.png
  VocaDbWeb/wwwroot/Content/ExtIcons/tanocstore.png
  VocaDbWeb/wwwroot/Content/Styles/ExtLinks.less
  VocaDbWeb/wwwroot/Scripts/Shared/WebLinkMatcher.ts
Labels: frontend, icons

#791 #602 Text color has low contrast on Dark Angel theme
  VocaDbWeb/wwwroot/Content/Styles/DarkAngel.less
Labels: frontend

#790 Replace expected exception with fluent assertions
  Tests/DatabaseTests/Queries/EventQueriesDatabaseTests.cs
  Tests/Domain/Tags/TagTests.cs
  Tests/Domain/Users/UserTests.cs
  Tests/Web/Controllers/DataAccess/AlbumQueriesTests.cs
  Tests/Web/Controllers/DataAccess/ArtistQueriesTests.cs
  Tests/Web/Controllers/DataAccess/DiscussionQueriesTests.cs
  Tests/Web/Controllers/DataAccess/EventQueriesTests.cs
  Tests/Web/Controllers/DataAccess/SongQueriesTests.cs
  Tests/Web/Controllers/DataAccess/TagQueriesTests.cs
  Tests/Web/Controllers/DataAccess/UserMessageQueriesTests.cs
  Tests/Web/Controllers/DataAccess/UserQueriesTests.cs
Labels: conversion
