Repository VocaDB/vocadb, pull requests merged in 2021-09, with the labels that each got.

#850 Increase the amount of visible events
  VocaDbModel/Service/OtherService.cs
  VocaDbWeb/Views/Shared/Partials/Shared/_EventThumbs.cshtml
  VocaDbWeb/wwwroot/Content/Styles/base.less
Labels: frontend

#963 Convert PlayList to React
  VocaDbWeb/Scripts/Components/Search/Partials/SongSearchList.tsx
  VocaDbWeb/Scripts/Components/Search/SearchIndex.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/PV/EmbedPV.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/PVRatingButtonsForIndex.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/PlayList.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Song/PVPreviewKnockout.tsx
  VocaDbWeb/Scripts/Components/useScript.ts
  VocaDbWeb/Scripts/Stores/PVRatingButtonsStore.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayerFile.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayerNico.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayerSoundCloud.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayerStore.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayerYoutube.ts
  VocaDbWeb/Scripts/Stores/PVs/PVPlayersFactory.ts
  VocaDbWeb/Scripts/Stores/Search/SearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/SongSearchStore.ts
  VocaDbWeb/Scripts/Stores/Song/PlayList/PlayListRepositoryForSongsAdapter.ts
  VocaDbWeb/Scripts/Stores/Song/PlayList/PlayListStore.ts
Labels: React, TODOs

#965 Feat/163 update URL on search page
  VocaDbWeb/Scripts/Components/Discussion/DiscussionFolders.tsx
  VocaDbWeb/Scripts/Components/Discussion/Partials/ViewTopic.tsx
  VocaDbWeb/Scripts/Components/Search/SearchIndex.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/LockingAutoComplete.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ReleaseEventLockingAutoComplete.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/SongLockingAutoComplete.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/TagFilters.tsx
  VocaDbWeb/Scripts/Components/SongList/SongListFeatured.tsx
  VocaDbWeb/Scripts/Components/User/UserIndex.tsx
  VocaDbWeb/Scripts/Components/useStoreWithPaging.ts
  VocaDbWeb/Scripts/Components/useStoreWithRouteParams.ts
  VocaDbWeb/Scripts/Components/useStoreWithUpdateResults.ts
  VocaDbWeb/Scripts/Stores/BasicEntryLinkStore.ts
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionIndexRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionIndexStore.ts
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionTopicRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionTopicStore.ts
  VocaDbWeb/Scripts/Stores/EditableCommentsStore.ts
  VocaDbWeb/Scripts/Stores/IStoreWithPaging.ts
  VocaDbWeb/Scripts/Stores/IStoreWithRouteParams.ts
  VocaDbWeb/Scripts/Stores/IStoreWithUpdateResults.ts
  VocaDbWeb/Scripts/Stores/PagedItemsStore.ts
  VocaDbWeb/Scripts/Stores/Search/AlbumSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/AnythingSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/ArtistFilters.ts
  VocaDbWeb/Scripts/Stores/Search/ArtistSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/EventSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/SearchCategoryBaseStore.ts
  VocaDbWeb/Scripts/Stores/Search/SearchRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/Search/SearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/SongSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/TagSearchStore.ts
  VocaDbWeb/Scripts/Stores/Song/PlayList/PlayListStore.ts
  VocaDbWeb/Scripts/Stores/SongList/FeaturedSongListsRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/SongList/FeaturedSongListsStore.ts
  VocaDbWeb/Scripts/Stores/SongList/SongListsBaseStore.ts
  VocaDbWeb/Scripts/Stores/User/ListUsersRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/User/ListUsersStore.ts
  VocaDbWeb/package-lock.json
  VocaDbWeb/package.json
Labels: search, documentation
