Repository VocaDB/vocadb, pull requests merged in 2022-09, with the labels that each got.

#1199 Added a new event enum value, "Festival"
  Tests/Domain/ReleaseEvents/ReleaseEventTypesTests.cs
  VocaDbModel/Domain/ReleaseEvents/EventCategory.cs
  VocaDbWeb/Scripts/Models/Events/EventCategory.ts
  VocaDbWeb/wwwroot/locales/en/VocaDb.Web.Resources.Domain.ReleaseEvents.json
  VocaDbWeb/wwwroot/locales/ja/VocaDb.Web.Resources.Domain.ReleaseEvents.json
Labels: documentation

#1223 Restore play queue items and index from the previous session
  VocaDbWeb/Scripts/Components/Shared/Partials/PV/EmbedPVPreview.tsx
  VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx
  VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayerContext.tsx
  VocaDbWeb/Scripts/Helpers/PlayQueueHelper.ts
  VocaDbWeb/Scripts/Pages/Artist/ArtistCollaborationAlbums.tsx
  VocaDbWeb/Scripts/Pages/Artist/ArtistMainAlbums.tsx
  VocaDbWeb/Scripts/Pages/Artist/ArtistSongs.tsx
  VocaDbWeb/Scripts/Pages/Comment/CommentIndex.tsx
  VocaDbWeb/Scripts/Pages/Discussion/DiscussionFolders.tsx
  VocaDbWeb/Scripts/Pages/Discussion/Partials/ViewTopic.tsx
  VocaDbWeb/Scripts/Pages/Playlist/PlaylistIndex.tsx
  VocaDbWeb/Scripts/Pages/Search/SearchIndex.tsx
  VocaDbWeb/Scripts/Pages/Song/SongLyrics.tsx
  VocaDbWeb/Scripts/Pages/Song/SongRankings.tsx
  VocaDbWeb/Scripts/Pages/SongList/SongListDetails.tsx
  VocaDbWeb/Scripts/Pages/SongList/SongListFeatured.tsx
  VocaDbWeb/Scripts/Pages/User/Partials/RatedSongs.tsx
  VocaDbWeb/Scripts/Pages/User/UserAlbums.tsx
  VocaDbWeb/Scripts/Pages/User/UserArtists.tsx
  VocaDbWeb/Scripts/Pages/User/UserCustomLists.tsx
  VocaDbWeb/Scripts/Pages/User/UserFavoriteSongs.tsx
  VocaDbWeb/Scripts/Pages/User/UserIndex.tsx
  VocaDbWeb/Scripts/Pages/User/UserSongs.tsx
  VocaDbWeb/Scripts/Stores/Artist/ArtistAlbumsStore.ts
  VocaDbWeb/Scripts/Stores/Artist/ArtistSongsStore.ts
  VocaDbWeb/Scripts/Stores/Comment/CommentListStore.ts
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionIndexStore.ts
  VocaDbWeb/Scripts/Stores/Discussion/DiscussionTopicStore.ts
  VocaDbWeb/Scripts/Stores/Search/AlbumSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/AnythingSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/ArtistSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/EventSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/SearchCategoryBaseStore.ts
  VocaDbWeb/Scripts/Stores/Search/SearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/SongSearchStore.ts
  VocaDbWeb/Scripts/Stores/Search/TagSearchStore.ts
  VocaDbWeb/Scripts/Stores/Song/RankingsStore.ts
  VocaDbWeb/Scripts/Stores/Song/SongLyricsStore.ts
  VocaDbWeb/Scripts/Stores/SongList/FeaturedSongListsStore.ts
  VocaDbWeb/Scripts/Stores/SongList/SongListStore.ts
  VocaDbWeb/Scripts/Stores/SongList/SongListsBaseStore.ts
  VocaDbWeb/Scripts/Stores/User/AlbumCollectionStore.ts
  VocaDbWeb/Scripts/Stores/User/FollowedArtistsStore.ts
  VocaDbWeb/Scripts/Stores/User/ListUsersStore.ts
  VocaDbWeb/Scripts/Stores/User/RatedSongsSearchStore.ts
  VocaDbWeb/Scripts/Stores/User/UserDetailsStore.ts
  VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueLocalStorageState.schema.json
  VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueStore.ts
  VocaDbWeb/Scripts/Stores/VdbPlayer/VdbPlayerLocalStorageState.schema.json
  VocaDbWeb/Scripts/Stores/VdbPlayer/VdbPlayerStore.ts
  VocaDbWeb/package-lock.json
  VocaDbWeb/package.json
Labels: TODOs

#1226 Convert user entry edits to React
  VocaDbWeb/Controllers/UserController.cs
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx
  VocaDbWeb/Scripts/DataContracts/ActivityEntry/ActivityEntryContract.ts
  VocaDbWeb/Scripts/Models/ActivityEntries/EntryEditEvent.ts
  VocaDbWeb/Scripts/Pages/ActivityEntry/ActivityEntryIndex.tsx
  VocaDbWeb/Scripts/Pages/User/UserEntryEdits.tsx
  VocaDbWeb/Scripts/Pages/User/UserOverview.tsx
  VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx
  VocaDbWeb/Scripts/Stores/ActivityEntry/ActivityEntryListRouteParams.schema.json
  VocaDbWeb/Scripts/Stores/ActivityEntry/ActivityEntryListStore.ts
  VocaDbWeb/Scripts/ViewModels/ActivityEntry/ActivityEntryListViewModel.ts
Labels: users, React

#1198 Convert user my settings to React
  Tests/Web/Controllers/DataAccess/UserQueriesTests.cs
  VocaDbModel/DataContracts/Users/ServerOnlyUpdateUserSettingsContract.cs
  VocaDbModel/DataContracts/Users/ServerOnlyUpdateUserSettingsForApiContract.cs
  VocaDbModel/DataContracts/Users/ServerOnlyUserForMySettingsContract.cs
  VocaDbModel/DataContracts/Users/ServerOnlyUserForMySettingsForApiContract.cs
  VocaDbModel/Database/Queries/UserQueries.cs
  VocaDbModel/Service/UserService.cs
  VocaDbModel/Utils/Config/SiteSettingsSection.cs
  VocaDbModel/VocaDb.Model.csproj
  VocaDbWeb/Controllers/Api/UserApiController.cs
  VocaDbWeb/Controllers/UserController.cs
  VocaDbWeb/Models/Shared/GlobalValues.cs
  VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Shared/SaveBtn.tsx
  VocaDbWeb/Scripts/Components/cultures.ts
  VocaDbWeb/Scripts/DataContracts/User/UpdateUserSettingsContract.ts
  VocaDbWeb/Scripts/DataContracts/User/UserForMySettingsContract.ts
  VocaDbWeb/Scripts/Models/Users/UserEmailOptions.ts
  VocaDbWeb/Scripts/Pages/Album/AlbumCreate.tsx
  VocaDbWeb/Scripts/Pages/Album/AlbumEdit.tsx
  VocaDbWeb/Scripts/Pages/Artist/ArtistCreate.tsx
  VocaDbWeb/Scripts/Pages/Artist/ArtistEdit.tsx
  VocaDbWeb/Scripts/Pages/Event/EventEdit.tsx
  VocaDbWeb/Scripts/Pages/Event/EventEditSeries.tsx
  VocaDbWeb/Scripts/Pages/Song/SongCreate.tsx
  VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
  VocaDbWeb/Scripts/Pages/SongList/SongListEdit.tsx
  VocaDbWeb/Scripts/Pages/Tag/TagEdit.tsx
  VocaDbWeb/Scripts/Pages/User/UserDetails.tsx
  VocaDbWeb/Scripts/Pages/User/UserMySettings.tsx
  VocaDbWeb/Scripts/Pages/User/UserOverview.tsx
  VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx
  VocaDbWeb/Scripts/Pages/Venue/VenueEdit.tsx
  VocaDbWeb/Scripts/Repositories/UserRepository.ts
  VocaDbWeb/Scripts/Shared/GlobalValues.ts
  VocaDbWeb/Scripts/Stores/User/MySettingsStore.ts
Labels: users, React

#1227 Convert user messages to React
  VocaDbWeb/Controllers/UserController.cs
  VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/BasicEntryLinkLockingAutoComplete.tsx
  VocaDbWeb/Scripts/Components/Shared/Partials/User/IconAndNameKnockout.tsx
  VocaDbWeb/Scripts/Pages/User/Partials/ComposeMessage.tsx
  VocaDbWeb/Scripts/Pages/User/Partials/UserMessageKnockout.tsx
  VocaDbWeb/Scripts/Pages/User/UserDetails.tsx
  VocaDbWeb/Scripts/Pages/User/UserMessages.tsx
  VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx
  VocaDbWeb/Scripts/Repositories/UserRepository.ts
  VocaDbWeb/Scripts/Shared/EntryUrlMapper.ts
  VocaDbWeb/Scripts/Stores/TopBarStore.ts
  VocaDbWeb/Scripts/Stores/User/UserMessagesStore.ts
Labels: users, React

#1232 Convert admin manage entry tag mappings to React
  VocaDbWeb/Controllers/AdminController.cs
  VocaDbWeb/Scripts/Pages/Admin/AdminIndex.tsx
  VocaDbWeb/Scripts/Pages/Admin/AdminManageEntryTagMappings.tsx
  VocaDbWeb/Scripts/Pages/Admin/AdminRoutes.tsx
  VocaDbWeb/Scripts/Stores/Admin/ManageEntryTagMappingsStore.ts
Labels: admin, React
